use std::fmt::Write;
use std::path::{Path, PathBuf};
use unideps_core::graph::DependencyNode;

pub struct CMakeGenerator;

impl CMakeGenerator {
    pub fn generate_targets_cmake(nodes: &[&DependencyNode]) -> String {
        let mut out = String::new();
        writeln!(&mut out, "# Generated by UniDeps. Do not edit.").unwrap();
        // include() runs in its own policy scope, so these only affect this file.
        writeln!(&mut out, "cmake_policy(SET CMP0057 NEW)").unwrap();
        writeln!(&mut out, "if(POLICY CMP0074)\n    cmake_policy(SET CMP0074 NEW)\nendif()").unwrap();
        writeln!(&mut out).unwrap();

        for node in nodes {
            if let Some(ref prefix) = node.install_prefix {
                let norm = prefix.to_string_lossy().replace('\\', "/");
                let var_name_upper = node.name.to_uppercase();
                let var_name_raw = &node.name;
                let mut vars = std::collections::BTreeSet::new();
                vars.insert(format!("UNIDEPS_{var_name_upper}_ROOT"));
                vars.insert(format!("{var_name_upper}_ROOT"));
                vars.insert(format!("{var_name_raw}_ROOT"));
                if let Some(ref imp) = node.import_name {
                    let imp_upper = imp.to_uppercase();
                    vars.insert(format!("{imp}_ROOT"));
                    vars.insert(format!("{imp_upper}_ROOT"));
                }
                for v in vars {
                    writeln!(&mut out, "set({v} \"{norm}\")").unwrap();
                }
                writeln!(&mut out, "list(PREPEND CMAKE_PREFIX_PATH \"{norm}\")").unwrap();
                writeln!(&mut out, "list(PREPEND CMAKE_MODULE_PATH \"{norm}\")").unwrap();
                writeln!(&mut out, "list(PREPEND CMAKE_FIND_ROOT_PATH \"{norm}\")").unwrap();
            }
        }
        writeln!(&mut out).unwrap();

        for node in nodes {
            if let Some(ref prefix) = node.install_prefix {
                let norm = prefix.to_string_lossy().replace('\\', "/");
                let name = &node.name;
                let explicit_import = node.import_name.as_deref();
                let target_name = format!("{name}::{name}");
                let ver_opt = node.tag.as_deref()
                    .or_else(|| node.commit.as_deref().map(|c| if c.len() >= 7 { &c[..7] } else { c }))
                    .or(node.branch.as_deref())
                    .or(node.version.as_deref());

                let should_auto_import =
                    node.auto_import || node.header_only || !node.include_dirs.is_empty() || !node.libraries.is_empty();

                if should_auto_import {
                    writeln!(&mut out, "if(NOT TARGET {target_name} AND NOT TARGET {name})").unwrap();

                    let mut inc_paths = Vec::new();
                    for inc in &node.include_dirs {
                        let full_path = if inc.is_absolute() {
                            inc.clone()
                        } else {
                            prefix.join(inc)
                        };
                        inc_paths.push(full_path.to_string_lossy().replace('\\', "/"));
                    }

                    let is_shared = node.shared.unwrap_or(node.config.shared);
                    let mut lib_paths: Vec<String> = Vec::new();
                    let mut unresolved: Vec<String> = Vec::new();
                    for lib in &node.libraries {
                        match Self::resolve_library_path(prefix, lib) {
                            Some(resolved) => lib_paths.push(resolved.to_string_lossy().replace('\\', "/")),
                            None => unresolved.push(lib.to_string_lossy().replace('\\', "/")),
                        }
                    }
                    let mut dll: Option<String> = node.binaries.first().map(|bin| {
                        let full = if bin.is_absolute() { bin.clone() } else { prefix.join(bin) };
                        full.to_string_lossy().replace('\\', "/")
                    });
                    if lib_paths.is_empty() && !node.header_only {
                        let (found_lib, found_dll) = Self::find_library_file(prefix, name, is_shared);
                        if let Some(l) = found_lib {
                            lib_paths.push(l.replace('\\', "/"));
                            if dll.is_none() {
                                dll = found_dll.map(|d| d.replace('\\', "/"));
                            }
                        }
                    } else if is_shared && dll.is_none() && let Some(first) = lib_paths.first() {
                        dll = Self::find_dll_for(prefix, Path::new(first));
                    }
                    for u in &unresolved {
                        writeln!(&mut out, "    message(WARNING \"UniDeps: library '{u}' of '{name}' not found in {norm}\")").unwrap();
                    }

                    let main_lib = if node.header_only { None } else { lib_paths.first().cloned() };
                    match main_lib {
                        None => {
                            if !node.header_only {
                                writeln!(&mut out, "    message(WARNING \"UniDeps: no library found for '{name}' in {norm}; importing it as header-only\")").unwrap();
                            }
                            writeln!(&mut out, "    add_library({target_name} INTERFACE IMPORTED)").unwrap();
                        }
                        Some(ref lib) => {
                            let is_dll_import = is_shared
                                && dll.as_deref().is_some_and(|d| d.to_lowercase().ends_with(".dll"));
                            if is_dll_import {
                                let dll_path = dll.as_deref().unwrap_or_default();
                                writeln!(&mut out, "    add_library({target_name} SHARED IMPORTED)").unwrap();
                                writeln!(&mut out, "    set_target_properties({target_name} PROPERTIES IMPORTED_LOCATION \"{dll_path}\" IMPORTED_IMPLIB \"{lib}\")").unwrap();
                            } else {
                                writeln!(&mut out, "    add_library({target_name} UNKNOWN IMPORTED)").unwrap();
                                writeln!(&mut out, "    set_target_properties({target_name} PROPERTIES IMPORTED_LOCATION \"{lib}\")").unwrap();
                            }
                            if lib_paths.len() > 1 {
                                let extra = lib_paths[1..].join(";");
                                writeln!(&mut out, "    set_property(TARGET {target_name} APPEND PROPERTY INTERFACE_LINK_LIBRARIES \"{extra}\")").unwrap();
                            }
                        }
                    }

                    if inc_paths.is_empty() {
                        let default_inc = format!("{norm}/include");
                        writeln!(&mut out, "    if(EXISTS \"{default_inc}\")").unwrap();
                        writeln!(&mut out, "        set_target_properties({target_name} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"{default_inc}\")").unwrap();
                        writeln!(&mut out, "    endif()").unwrap();
                    } else {
                        let inc_joined = inc_paths.join(";");
                        writeln!(&mut out, "    set_target_properties({target_name} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"{inc_joined}\")").unwrap();
                    }
                    writeln!(&mut out, "endif()").unwrap();

                    if let Some(imp) = explicit_import {
                        writeln!(&mut out, "if(NOT TARGET {imp}::{imp} AND TARGET {target_name})").unwrap();
                        writeln!(&mut out, "    add_library({imp}::{imp} INTERFACE IMPORTED)").unwrap();
                        writeln!(&mut out, "    target_link_libraries({imp}::{imp} INTERFACE {target_name})").unwrap();
                        writeln!(&mut out, "endif()").unwrap();
                        if imp != name {
                            writeln!(&mut out, "if(NOT TARGET {imp} AND TARGET {target_name})").unwrap();
                            writeln!(&mut out, "    add_library({imp} INTERFACE IMPORTED)").unwrap();
                            writeln!(&mut out, "    target_link_libraries({imp} INTERFACE {target_name})").unwrap();
                            writeln!(&mut out, "endif()").unwrap();
                        }
                    }
                    writeln!(&mut out, "if(NOT TARGET {name} AND TARGET {target_name})").unwrap();
                    writeln!(&mut out, "    add_library({name} INTERFACE IMPORTED)").unwrap();
                    writeln!(&mut out, "    target_link_libraries({name} INTERFACE {target_name})").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    if !node.dependencies.is_empty() {
                        writeln!(&mut out, "if(TARGET {target_name})").unwrap();
                        for dep in &node.dependencies {
                            let dep_node = nodes.iter().find(|n| n.name == *dep);
                            let dep_import = dep_node.and_then(|n| n.import_name.as_deref());
                            if let Some(imp) = dep_import {
                                writeln!(&mut out, "    if(TARGET {imp}::{imp})").unwrap();
                                writeln!(&mut out, "        target_link_libraries({target_name} INTERFACE {imp}::{imp})").unwrap();
                                writeln!(&mut out, "    elseif(TARGET {imp})").unwrap();
                                writeln!(&mut out, "        target_link_libraries({target_name} INTERFACE {imp})").unwrap();
                                writeln!(&mut out, "    elseif(TARGET {dep}::{dep})").unwrap();
                                writeln!(&mut out, "        target_link_libraries({target_name} INTERFACE {dep}::{dep})").unwrap();
                                writeln!(&mut out, "    elseif(TARGET {dep})").unwrap();
                                writeln!(&mut out, "        target_link_libraries({target_name} INTERFACE {dep})").unwrap();
                                writeln!(&mut out, "    endif()").unwrap();
                            } else {
                                writeln!(&mut out, "    if(TARGET {dep}::{dep})").unwrap();
                                writeln!(&mut out, "        target_link_libraries({target_name} INTERFACE {dep}::{dep})").unwrap();
                                writeln!(&mut out, "    elseif(TARGET {dep})").unwrap();
                                writeln!(&mut out, "        target_link_libraries({target_name} INTERFACE {dep})").unwrap();
                                writeln!(&mut out, "    endif()").unwrap();
                            }
                        }
                        writeln!(&mut out, "endif()").unwrap();
                    }

                    let display_name = explicit_import.unwrap_or(name);
                    let targets = if let Some(imp) = explicit_import {
                        if imp == name {
                            target_name.clone()
                        } else {
                            format!("{target_name};{imp}::{imp}")
                        }
                    } else {
                        target_name.clone()
                    };
                    let ver_str = ver_opt.map(|v| format!(" (version {v})")).unwrap_or_default();
                    writeln!(&mut out, "message(STATUS \"Imported: {display_name} ({targets}) ({norm}){ver_str}\")").unwrap();
                } else {
                    let initial_pkg = explicit_import.unwrap_or(name);
                    writeln!(&mut out, "set(_unideps_{name}_imported_pkg \"{initial_pkg}\")").unwrap();
                    if let Some(ver) = ver_opt {
                        writeln!(&mut out, "set(_unideps_{name}_ver \"{ver}\")").unwrap();
                    } else {
                        writeln!(&mut out, "set(_unideps_{name}_ver \"\")").unwrap();
                    }

                    writeln!(&mut out, "if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.21)").unwrap();
                    writeln!(&mut out, "    get_property(_unideps_{name}_targets_before DIRECTORY PROPERTY IMPORTED_TARGETS)").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    let mut attempted_packages = Vec::new();
                    if let Some(imp) = explicit_import {
                        attempted_packages.push(imp.to_string());
                    } else {
                        attempted_packages.extend(Self::find_cmake_configs(prefix));
                        if attempted_packages.is_empty() {
                            attempted_packages.push(name.to_string());
                        }
                    }

                    let found_var = format!("_unideps_{name}_found");
                    writeln!(&mut out, "set({found_var} FALSE)").unwrap();

                    for pkg in &attempted_packages {
                        let pkg_upper = pkg.to_uppercase();
                        writeln!(&mut out, "if(NOT {found_var})").unwrap();
                        writeln!(&mut out, "    find_package({pkg} CONFIG QUIET)").unwrap();
                        writeln!(&mut out, "    if({pkg}_FOUND OR {pkg_upper}_FOUND)").unwrap();
                        writeln!(&mut out, "        set({found_var} TRUE)").unwrap();
                        writeln!(&mut out, "        set(_unideps_{name}_imported_pkg \"{pkg}\")").unwrap();
                        writeln!(&mut out, "    endif()").unwrap();
                        writeln!(&mut out, "endif()").unwrap();
                    }

                    writeln!(&mut out, "if(NOT {found_var})").unwrap();
                    writeln!(&mut out, "    message(FATAL_ERROR \"UniDeps: could not resolve dependency '{name}' via find_package CONFIG in {norm}\")").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    writeln!(&mut out, "set(_unideps_{name}_new_targets \"\")").unwrap();
                    writeln!(&mut out, "if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.21)").unwrap();
                    writeln!(&mut out, "    get_property(_unideps_{name}_targets_after DIRECTORY PROPERTY IMPORTED_TARGETS)").unwrap();
                    writeln!(&mut out, "    foreach(_t IN LISTS _unideps_{name}_targets_after)").unwrap();
                    writeln!(&mut out, "        if(NOT _t IN_LIST _unideps_{name}_targets_before)").unwrap();
                    writeln!(&mut out, "            list(APPEND _unideps_{name}_new_targets \"${{_t}}\")").unwrap();
                    writeln!(&mut out, "        endif()").unwrap();
                    writeln!(&mut out, "    endforeach()").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    writeln!(&mut out, "if(NOT _unideps_{name}_new_targets)").unwrap();
                    writeln!(&mut out, "    if(TARGET {name}::{name})").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_new_targets \"{name}::{name}\")").unwrap();
                    writeln!(&mut out, "    elseif(TARGET ${{_unideps_{name}_imported_pkg}}::${{_unideps_{name}_imported_pkg}})").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_new_targets \"${{_unideps_{name}_imported_pkg}}::${{_unideps_{name}_imported_pkg}}\")").unwrap();
                    writeln!(&mut out, "    elseif(TARGET {name})").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_new_targets \"{name}\")").unwrap();
                    writeln!(&mut out, "    elseif(TARGET ${{_unideps_{name}_imported_pkg}})").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_new_targets \"${{_unideps_{name}_imported_pkg}}\")").unwrap();
                    writeln!(&mut out, "    else()").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_new_targets \"${{_unideps_{name}_imported_pkg}}\")").unwrap();
                    writeln!(&mut out, "    endif()").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    writeln!(&mut out, "if(NOT _unideps_{name}_ver)").unwrap();
                    writeln!(&mut out, "    string(TOUPPER \"${{_unideps_{name}_imported_pkg}}\" _unideps_{name}_imported_pkg_upper)").unwrap();
                    writeln!(&mut out, "    if(DEFINED ${{_unideps_{name}_imported_pkg}}_VERSION AND NOT \"${{${{_unideps_{name}_imported_pkg}}_VERSION}}\" STREQUAL \"\")").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_ver \"${{${{_unideps_{name}_imported_pkg}}_VERSION}}\")").unwrap();
                    writeln!(&mut out, "    elseif(DEFINED ${{_unideps_{name}_imported_pkg_upper}}_VERSION AND NOT \"${{${{_unideps_{name}_imported_pkg_upper}}_VERSION}}\" STREQUAL \"\")").unwrap();
                    writeln!(&mut out, "        set(_unideps_{name}_ver \"${{${{_unideps_{name}_imported_pkg_upper}}_VERSION}}\")").unwrap();
                    writeln!(&mut out, "    endif()").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    writeln!(&mut out, "set(_unideps_{name}_ver_str \"\")").unwrap();
                    writeln!(&mut out, "if(_unideps_{name}_ver)").unwrap();
                    writeln!(&mut out, "    set(_unideps_{name}_ver_str \" (version ${{_unideps_{name}_ver}})\")").unwrap();
                    writeln!(&mut out, "endif()").unwrap();

                    writeln!(&mut out, "message(STATUS \"Imported: ${{_unideps_{name}_imported_pkg}} (${{_unideps_{name}_new_targets}}) ({norm})${{_unideps_{name}_ver_str}}\")").unwrap();
                }
            }
        }

        writeln!(&mut out).unwrap();
        out
    }

    fn find_cmake_configs(prefix: &Path) -> Vec<String> {
        let mut configs = Vec::new();
        let search_dirs = [
            prefix.join("lib").join("cmake"),
            prefix.join("cmake"),
            prefix.join("share"),
            prefix.to_path_buf(),
        ];

        for dir in &search_dirs {
            if dir.exists() {
                for entry in walkdir::WalkDir::new(dir).max_depth(5).into_iter().filter_map(|e| e.ok()) {
                    let fname = entry.file_name().to_string_lossy();
                    if let Some(pkg) = fname.strip_suffix("Config.cmake").or_else(|| fname.strip_suffix("-config.cmake"))
                        && !pkg.is_empty() && !configs.contains(&pkg.to_string()) {
                            configs.push(pkg.to_string());
                        }
                }
            }
        }
        configs
    }

    pub fn resolve_library_path(prefix: &Path, lib_hint: &Path) -> Option<PathBuf> {
        if lib_hint.is_absolute() && lib_hint.is_file() {
            return Some(lib_hint.to_path_buf());
        }

        let direct = prefix.join(lib_hint);
        if direct.is_file() {
            return Some(direct);
        }

        let raw_name = lib_hint.file_name()?.to_string_lossy();
        let stem = lib_hint
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| raw_name.to_string());
        let clean_stem = stem.strip_prefix("lib").unwrap_or(&stem);

        let search_dirs = [
            if let Some(parent) = lib_hint.parent() {
                if !parent.as_os_str().is_empty() {
                    prefix.join(parent)
                } else {
                    prefix.join("lib")
                }
            } else {
                prefix.join("lib")
            },
            prefix.join("lib"),
            prefix.to_path_buf(),
        ];

        let candidates = [
            format!("{clean_stem}.lib"),
            format!("lib{clean_stem}.a"),
            format!("lib{clean_stem}.so"),
            format!("lib{clean_stem}.dylib"),
            format!("lib{clean_stem}.lib"),
            format!("{clean_stem}.a"),
            format!("{clean_stem}.so"),
            format!("{clean_stem}.dylib"),
            format!("{clean_stem}.dll.a"),
            format!("{stem}.lib"),
            format!("lib{stem}.a"),
            format!("lib{stem}.so"),
            format!("lib{stem}.dylib"),
            format!("{stem}.a"),
            format!("{stem}.so"),
            format!("{stem}.dylib"),
        ];

        for dir in &search_dirs {
            if dir.exists() {
                for cand in &candidates {
                    let candidate_path = dir.join(cand);
                    if candidate_path.is_file() {
                        return Some(candidate_path);
                    }
                }
            }
        }

        None
    }

    fn find_dll_for(prefix: &Path, lib: &Path) -> Option<String> {
        let stem = lib.file_stem()?.to_string_lossy().to_string();
        let clean_stem = stem.strip_prefix("lib").unwrap_or(&stem).to_string();
        let bin_dir = prefix.join("bin");
        [format!("{clean_stem}.dll"), format!("lib{clean_stem}.dll"), format!("{stem}.dll")]
            .into_iter()
            .map(|c| bin_dir.join(c))
            .find(|p| p.exists())
            .map(|p| p.to_string_lossy().replace('\\', "/"))
    }

    fn find_library_file(prefix: &Path, name: &str, shared: bool) -> (Option<String>, Option<String>) {
        let lib_dir = prefix.join("lib");
        let bin_dir = prefix.join("bin");

        if !lib_dir.exists() {
            return (None, None);
        }

        let clean_name = name.strip_prefix("lib").unwrap_or(name).to_lowercase();
        let name_lower = name.to_lowercase();

        let mut named_static = None;
        let mut named_implib = None;
        let mut fallback_static = None;
        let mut fallback_implib = None;

        if let Ok(entries) = std::fs::read_dir(&lib_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                let fname = path.file_name().unwrap_or_default().to_string_lossy();
                let fname_lower = fname.to_lowercase();

                let is_match = fname_lower.contains(&clean_name) || fname_lower.contains(&name_lower);

                if fname_lower.ends_with("static.lib") || fname_lower.ends_with(".a") {
                    if is_match && named_static.is_none() {
                        named_static = Some(path.to_string_lossy().to_string());
                    } else if fallback_static.is_none() {
                        fallback_static = Some(path.to_string_lossy().to_string());
                    }
                } else if fname_lower.ends_with(".lib")
                    || fname_lower.ends_with(".so")
                    || fname_lower.contains(".so.")
                    || fname_lower.ends_with(".dylib")
                {
                    if is_match && named_implib.is_none() {
                        named_implib = Some(path.to_string_lossy().to_string());
                    } else if fallback_implib.is_none() {
                        fallback_implib = Some(path.to_string_lossy().to_string());
                    }
                }
            }
        }

        let static_lib = named_static.or(fallback_static);
        let implib = named_implib.or(fallback_implib);

        if !shared && static_lib.is_some() {
            return (static_lib, None);
        }

        let mut dll_path = None;
        if bin_dir.exists()
            && let Ok(entries) = std::fs::read_dir(&bin_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    let fname = path.file_name().unwrap_or_default().to_string_lossy();
                    let fname_lower = fname.to_lowercase();
                    if fname_lower.ends_with(".dll") || fname_lower.ends_with(".so") || fname_lower.contains(".so.") || fname_lower.ends_with(".dylib") {
                        if fname_lower.contains(&clean_name) || fname_lower.contains(&name_lower) {
                            dll_path = Some(path.to_string_lossy().to_string());
                            break;
                        } else if dll_path.is_none() {
                            dll_path = Some(path.to_string_lossy().to_string());
                        }
                    }
                }
            }

        if shared && implib.is_some() {
            (implib, dll_path)
        } else if static_lib.is_some() {
            (static_lib, None)
        } else {
            (implib, dll_path)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use unideps_core::manifest::{DependencyDetails, DependencySpec};

    #[test]
    fn test_cmake_generator_find_package_mode() {
        let spec = DependencySpec::Detailed(DependencyDetails {
            import_name: Some("WebP".into()),
            tag: Some("v1.3.2".into()),
            ..Default::default()
        });
        let mut node = DependencyNode::from_target_dep("webp", &spec);
        node.install_prefix = Some(std::path::PathBuf::from("C:/mock/prefix"));

        let content = CMakeGenerator::generate_targets_cmake(&[&node]);
        assert!(content.contains("find_package(WebP CONFIG QUIET)"));
        assert!(content.contains("message(FATAL_ERROR \"UniDeps: could not resolve dependency 'webp' via find_package CONFIG in C:/mock/prefix\")"));
        assert!(!content.contains("add_library(webp::webp UNKNOWN IMPORTED)"));
        assert!(content.contains("set(_unideps_webp_ver \"v1.3.2\")"));
        assert!(content.contains("message(STATUS \"Imported: ${_unideps_webp_imported_pkg} (${_unideps_webp_new_targets}) (C:/mock/prefix)${_unideps_webp_ver_str}\")"));
    }

    #[test]
    fn test_cmake_generator_auto_import_mode() {
        let spec = DependencySpec::Detailed(DependencyDetails {
            auto_import: Some(true),
            version: Some("2.0.0".into()),
            ..Default::default()
        });
        let mut node = DependencyNode::from_target_dep("mylib", &spec);
        node.install_prefix = Some(std::path::PathBuf::from("C:/mock/prefix"));

        let content = CMakeGenerator::generate_targets_cmake(&[&node]);
        assert!(content.contains("add_library(mylib::mylib INTERFACE IMPORTED)"));
        assert!(!content.contains("find_package("));
        assert!(content.contains("message(STATUS \"Imported: mylib (mylib::mylib) (C:/mock/prefix) (version 2.0.0)\")"));
    }

    #[test]
    fn test_resolve_library_path() {
        let temp = tempfile::tempdir().unwrap();
        let prefix = temp.path();
        let lib_dir = prefix.join("lib");
        std::fs::create_dir_all(&lib_dir).unwrap();
        std::fs::write(lib_dir.join("yuv.lib"), b"dummy").unwrap();

        let resolved = CMakeGenerator::resolve_library_path(prefix, Path::new("lib/yuv"));
        assert_eq!(resolved, Some(lib_dir.join("yuv.lib")));

        let resolved_stem = CMakeGenerator::resolve_library_path(prefix, Path::new("yuv"));
        assert_eq!(resolved_stem, Some(lib_dir.join("yuv.lib")));

        // A library named like a directory must resolve to the file, not to `<prefix>/lib`.
        std::fs::write(lib_dir.join("liblib.a"), b"dummy").unwrap();
        let resolved_lib = CMakeGenerator::resolve_library_path(prefix, Path::new("lib"));
        assert_eq!(resolved_lib, Some(lib_dir.join("liblib.a")));
    }

    fn node_with(spec: DependencyDetails, prefix: &Path) -> DependencyNode {
        let mut node = DependencyNode::from_target_dep("pkg", &DependencySpec::Detailed(spec));
        node.install_prefix = Some(prefix.to_path_buf());
        node
    }

    #[test]
    fn test_header_only_is_interface() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(temp.path().join("include")).unwrap();
        let node = node_with(DependencyDetails { header_only: Some(true), ..Default::default() }, temp.path());
        let content = CMakeGenerator::generate_targets_cmake(&[&node]);
        assert!(content.contains("add_library(pkg::pkg INTERFACE IMPORTED)"));
        assert!(!content.contains("UNKNOWN IMPORTED"));
        assert!(!content.contains("find_package("));
    }

    #[test]
    fn test_auto_import_without_library_does_not_emit_unknown_target() {
        let temp = tempfile::tempdir().unwrap();
        let node = node_with(DependencyDetails { auto_import: Some(true), ..Default::default() }, temp.path());
        let content = CMakeGenerator::generate_targets_cmake(&[&node]);
        assert!(content.contains("add_library(pkg::pkg INTERFACE IMPORTED)"));
        assert!(content.contains("message(WARNING"));
    }

    #[test]
    fn test_all_libraries_are_linked() {
        let temp = tempfile::tempdir().unwrap();
        let lib = temp.path().join("lib");
        std::fs::create_dir_all(&lib).unwrap();
        std::fs::write(lib.join("libfoo.a"), b"").unwrap();
        std::fs::write(lib.join("libbar.a"), b"").unwrap();
        let node = node_with(
            DependencyDetails { libraries: vec!["foo".into(), "bar".into(), "missing".into()], ..Default::default() },
            temp.path(),
        );
        let content = CMakeGenerator::generate_targets_cmake(&[&node]);
        let norm = lib.to_string_lossy().replace('\\', "/");
        assert!(content.contains(&format!("IMPORTED_LOCATION \"{norm}/libfoo.a\"")));
        assert!(content.contains(&format!("INTERFACE_LINK_LIBRARIES \"{norm}/libbar.a\"")));
        assert!(content.contains("library 'missing' of 'pkg' not found"));
    }

    #[test]
    fn test_shared_dll_import() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(temp.path().join("lib")).unwrap();
        std::fs::create_dir_all(temp.path().join("bin")).unwrap();
        std::fs::write(temp.path().join("lib/foo.lib"), b"").unwrap();
        std::fs::write(temp.path().join("bin/foo.dll"), b"").unwrap();
        let node = node_with(
            DependencyDetails { shared: Some(true), libraries: vec!["foo".into()], ..Default::default() },
            temp.path(),
        );
        let content = CMakeGenerator::generate_targets_cmake(&[&node]);
        assert!(content.contains("add_library(pkg::pkg SHARED IMPORTED)"));
        assert!(content.contains("foo.dll\" IMPORTED_IMPLIB"));
    }
}
